### ISSUE TITLE
skill表查询优化

### ISSUE THREAD

**Issue by crazyjohn** [serverBiatch/teamWiki#31]
> 记录一次表查询缓慢的优化。
## 0. 表象

@niepantzy 报合服以后大量延时的sql:

![](http://i.imgur.com/KmTzJPe.jpg)

原sql是这样的：

```
List<SkillEntity> skillEntities = HawkDBManager.getInstance().query(
                "from SkillEntity where playerId = ? and invalid = 0 order by id asc", playerId);
```
## 1. 找问题
1. 先看下表数据大小
   
   ```
   mysql> select count(*) from skill;
   +----------+
   | count(*) |
   +----------+
   |   366027 |
   +----------+
   1 row in set (0.06 sec)
   ```
   
   大概是36w行
2. 看下表索引的情况
   
   ```
   mysql> show index from skill \G;
   *************************** 1. row ***************************
           Table: skill
      Non_unique: 0
        Key_name: PRIMARY
    Seq_in_index: 1
     Column_name: id
       Collation: A
     Cardinality: 353991
        Sub_part: NULL
          Packed: NULL
            Null: 
      Index_type: BTREE
         Comment: 
   Index_comment: 
   1 row in set (0.00 sec)
   ```
   
   只有一个主键。
3. 看下当前sql的执行计划
   
   ```
   mysql> explain select * from skill where playerId = 1001 and invalid = 0 order by id asc\G;
   *************************** 1. row ***************************
              id: 1
     select_type: SIMPLE
           table: skill
            type: index
   possible_keys: NULL
             key: PRIMARY
         key_len: 4
             ref: NULL
            rows: 353991
           Extra: Using where
   1 row in set (0.00 sec)
   ```
   
   几个信息：1查询类型使用了index索引，也就是会遍历所有主键；2key使用了当前的主键；3rows达到了35w。尤其是最后一条信息，这是肯定不行的，几乎进行了全表扫描，效率必然很低。
4. 执行查询看看情况
   
   ```
   mysql> select * from skill where playerId = 1001 and invalid = 0 order by id asc\G;
   *************************** 1. row ***************************
           id: 3224
     playerId: 1001
       roleId: 0
       itemId: 12
   skillLevel: 1
       status: 0
          exp: 0
   createTime: 2014-09-16 19:07:14
   updateTime: 2014-09-16 19:07:14
      invalid: 0
   *************************** 2. row ***************************
           id: 24058
     playerId: 1001
       roleId: 0
       itemId: 11
   skillLevel: 1
       status: 0
          exp: 0
   createTime: 2014-09-16 12:36:58
   updateTime: 2014-09-16 12:36:58
      invalid: 0
   2 rows in set (0.15 sec)
   ```
   
   共查询出了2条信息，耗时150毫秒，果然比较慢。
5. 尝试添加playerId索引
   
   ```
   mysql> create index playerId_index on skill (playerId);
   Query OK, 0 rows affected (0.65 sec)
   Records: 0  Duplicates: 0  Warnings: 0
   
   mysql> show index from skill \G;
   *************************** 1. row ***************************
           Table: skill
      Non_unique: 0
        Key_name: PRIMARY
    Seq_in_index: 1
     Column_name: id
       Collation: A
     Cardinality: 353991
        Sub_part: NULL
          Packed: NULL
            Null: 
      Index_type: BTREE
         Comment: 
   Index_comment: 
   *************************** 2. row ***************************
           Table: skill
      Non_unique: 1
        Key_name: playerId_index
    Seq_in_index: 1
     Column_name: playerId
       Collation: A
     Cardinality: 117997
        Sub_part: NULL
          Packed: NULL
            Null: 
      Index_type: BTREE
         Comment: 
   Index_comment: 
   2 rows in set (0.00 sec)
   ```
   
   创建索引，并且生效。
6. 接着看查询计划
   
   ```
   mysql> explain select * from skill where playerId = 1001 and invalid = 0 order by id asc\G;
   *************************** 1. row ***************************
              id: 1
     select_type: SIMPLE
           table: skill
            type: ref
   possible_keys: playerId_index
             key: playerId_index
         key_len: 4
             ref: const
            rows: 2
           Extra: Using where
   1 row in set (0.00 sec)
   ```
   
   几个重要信息：1查询类型使用ref引用；2使用playerId_index作为了键值；3目标rows只有2行。效果不错。
7. 执行看效果
   
   ```
   mysql> select * from skill where playerId = 1001 and invalid = 0 order by id asc\G;
   *************************** 1. row ***************************
           id: 3224
     playerId: 1001
       roleId: 0
       itemId: 12
   skillLevel: 1
       status: 0
          exp: 0
   createTime: 2014-09-16 19:07:14
   updateTime: 2014-09-16 19:07:14
      invalid: 0
   *************************** 2. row ***************************
           id: 24058
     playerId: 1001
       roleId: 0
       itemId: 11
   skillLevel: 1
       status: 0
          exp: 0
   createTime: 2014-09-16 12:36:58
   updateTime: 2014-09-16 12:36:58
      invalid: 0
   2 rows in set (0.00 sec)
   ```
   
   效果立竿见影。
## 2. 总结
- 遇到上述这类问题的时候先去分析下执行慢的原因，一层层找到性能消耗的点，然后针对性的进行优化。
- 索引是把双刃剑，知其然知其所以然才能使用好它，切不要认为索引越多越好，索引越多效率越高，了解了mysql的内部机制，才可以做好优化。
- 最后这点写给某人，一教点新东西就丢开手中的事情去乱搞。一步步来，还是那句话，做好手头事，新知识的话，先去了解，然后实践，一步步来，实践出真知。
